# Generated by Django 5.2.8 on 2026-02-13 00:42

import api.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id_annee', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'annees_escolaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id_classe', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'classes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id_etab', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=500)),
                ('adresse', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('PRIVE', 'Privé'), ('PUBLIC', 'Public')], default='PRIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'etablissements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id_matiere', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'matieres',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NiveauEtude',
            fields=[
                ('id_niveau', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'niveaux',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id_poste', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'postes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bibliotheque',
            fields=[
                ('id_doc', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('nom_fichier', models.CharField(blank=True, max_length=255, null=True)),
                ('fichier', models.FileField(upload_to='documents/photos/eleve/photo/')),
                ('type_fichier', models.CharField(max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.anneescolaire')),
            ],
            options={
                'db_table': 'bibliotheque',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Disponible',
            fields=[
                ('id_disponible', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scolarite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponible_classe', to='api.classe')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponible_etablissement', to='api.etablissement')),
            ],
            options={
                'db_table': 'disponibles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('matricule', models.CharField(blank=True, max_length=20, null=True)),
                ('id_eleve', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('genre', models.CharField(blank=True, max_length=15, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('nom_prenom_parent_1', models.CharField(blank=True, max_length=200, null=True)),
                ('tel1', models.CharField(blank=True, max_length=20, null=True)),
                ('nom_prenom_parent_2', models.CharField(blank=True, max_length=200, null=True)),
                ('tel2', models.CharField(blank=True, max_length=20, null=True)),
                ('email_parent_1', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_parent_2', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eleve_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'eleves',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentEleve',
            fields=[
                ('id_doc', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('nom_fichier', models.CharField(blank=True, max_length=255, null=True)),
                ('fichier', models.FileField(max_length=700, upload_to=api.models.upload_eleve_path)),
                ('type_fichier', models.CharField(max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.anneescolaire')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_eleve', to='api.eleve')),
            ],
            options={
                'db_table': 'documentEleves',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id_ens', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('genre', models.CharField(blank=True, max_length=15, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('tel1', models.CharField(blank=True, max_length=20, null=True)),
                ('tel2', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enseignant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enseignants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentEnseignant',
            fields=[
                ('id_doc', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('nom_fichier', models.CharField(blank=True, max_length=255, null=True)),
                ('fichier', models.FileField(max_length=700, upload_to=api.models.upload_enseignant_path)),
                ('type_fichier', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.anneescolaire')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_enseignant', to='api.enseignant')),
            ],
            options={
                'db_table': 'documentEnseignants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cour',
            fields=[
                ('id_cours', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=250)),
                ('coefficient', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cour_annee_scolaire', to='api.anneescolaire')),
                ('disponible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cour_disponible', to='api.disponible')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cour_enseignant', to='api.enseignant')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cour_etablissement', to='api.etablissement')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cour_matiere', to='api.matiere')),
            ],
            options={
                'db_table': 'cours',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enseigne',
            fields=[
                ('id_enseigne', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('periode', models.CharField(blank=True, max_length=50, null=True)),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseigne_annee_scolaire', to='api.anneescolaire')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseigne_enseignant', to='api.enseignant')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseigne_etablissement', to='api.etablissement')),
            ],
            options={
                'db_table': 'enseignes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id_emploi', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jour', models.CharField(blank=True, max_length=20, null=True)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.anneescolaire')),
                ('cour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires_cour', to='api.cour')),
                ('disponible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires_disponible', to='api.disponible')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.etablissement')),
            ],
            options={
                'db_table': 'emplois_du_temps',
                'ordering': ['jour', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='DocumentEtablissement',
            fields=[
                ('id_doc', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('nom_fichier', models.CharField(blank=True, max_length=255, null=True)),
                ('fichier', models.FileField(max_length=700, upload_to=api.models.upload_etablissement_path)),
                ('type_fichier', models.CharField(max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.anneescolaire')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_etablissement', to='api.etablissement')),
            ],
            options={
                'db_table': 'documentEtablissements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='anneescolaire',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.etablissement'),
        ),
        migrations.CreateModel(
            name='Inscrit',
            fields=[
                ('id_inscrit', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.anneescolaire')),
                ('disponible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscrit_disponible', to='api.disponible')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscrit_eleve', to='api.eleve')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscrit_etablissement', to='api.etablissement')),
            ],
            options={
                'db_table': 'inscrits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id_msg', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('objet', models.CharField(max_length=300)),
                ('contenu', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='messages/attachments/')),
                ('date', models.DateField(blank=True, null=True)),
                ('heure', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.anneescolaire')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus_eleve', to='api.eleve')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Message_etablissement', to='api.etablissement')),
                ('expediteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='classe',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classe_niveau', to='api.niveauetude'),
        ),
        migrations.CreateModel(
            name='Scolarite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranche', models.CharField(max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.anneescolaire')),
                ('inscrit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scolarites', to='api.inscrit')),
            ],
            options={
                'db_table': 'scolarites',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id_staff', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, max_length=15, null=True)),
                ('tel1', models.CharField(blank=True, max_length=20, null=True)),
                ('tel2', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staffs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentStaff',
            fields=[
                ('id_doc', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('nom_fichier', models.CharField(blank=True, max_length=255, null=True)),
                ('fichier', models.FileField(max_length=700, upload_to=api.models.upload_staff_path)),
                ('type_fichier', models.CharField(max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.anneescolaire')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_staff', to='api.staff')),
            ],
            options={
                'db_table': 'documentStaffs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id_depense', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_depense', models.DateField()),
                ('categorie', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='depenses/justificatifs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.anneescolaire')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depense_etablissement', to='api.etablissement')),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.staff')),
            ],
            options={
                'db_table': 'depenses',
                'ordering': ['-date_depense'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id_eval', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('typeEval', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('periode', models.PositiveSmallIntegerField(help_text='1 pour Trim1/Sem1, 2 pour Trim2/Sem2, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.anneescolaire')),
                ('cour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_cour', to='api.cour')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_eleve', to='api.eleve')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_etablissement', to='api.etablissement')),
            ],
            options={
                'db_table': 'evaluations',
                'ordering': ['-created_at'],
                'unique_together': {('eleve', 'cour', 'typeEval', 'periode', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id_presence', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='PRESENT', max_length=15, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.anneescolaire')),
                ('cour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_cour', to='api.cour')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_eleve', to='api.eleve')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_etablissement', to='api.etablissement')),
            ],
            options={
                'db_table': 'presences',
                'ordering': ['-created_at'],
                'unique_together': {('eleve', 'cour', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Occupe',
            fields=[
                ('id_occupe', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_etablissement', to='api.etablissement')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.poste')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_occupations', to='api.staff')),
            ],
            options={
                'db_table': 'occupes',
                'ordering': ['-created_at'],
                'unique_together': {('staff', 'etablissement')},
            },
        ),
    ]
