# Generated by Django 5.2.8 on 2025-11-15 20:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cour',
            fields=[
                ('id_cours', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coefficient', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cour_classe', to='api.classe')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cour_enseignant', to='api.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cour_matiere', to='api.matiere')),
            ],
            options={
                'db_table': 'cours',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Disponible',
            fields=[
                ('id_disponible', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponible_classe', to='api.classe')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponible_etablissement', to='api.etablissement')),
            ],
            options={
                'db_table': 'Disponibles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enseigne',
            fields=[
                ('id_enseigne', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseigne_enseignant', to='api.enseignant')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseigne_etablissement', to='api.etablissement')),
            ],
            options={
                'db_table': 'enseignes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inscrit',
            fields=[
                ('id_inscrit', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscrit_classe', to='api.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscrit_eleve', to='api.eleve')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscrit_etablissement', to='api.etablissement')),
            ],
            options={
                'db_table': 'inscrits',
                'ordering': ['-created_at'],
            },
        ),
    ]
