# Generated by Django 5.2.8 on 2025-11-18 21:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cour_disponible_enseigne_inscrit'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='sexe',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='sexe',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='staff_poste', to='api.poste'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='disponible',
            table='disponibles',
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id_depense', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(blank=True, max_length=500, null=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depense_etablissement', to='api.etablissement')),
            ],
            options={
                'db_table': 'depenses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Devoir',
            fields=[
                ('id_devoir', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoir_cour', to='api.cour')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoir_eleve', to='api.eleve')),
            ],
            options={
                'db_table': 'devoirs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interrogation',
            fields=[
                ('id_interro', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interrogation_cour', to='api.cour')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interrogation_eleve', to='api.eleve')),
            ],
            options={
                'db_table': 'interrogations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id_presence', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_cour', to='api.cour')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_eleve', to='api.eleve')),
            ],
            options={
                'db_table': 'presences',
                'ordering': ['-created_at'],
            },
        ),
    ]
