# Generated by Django 5.2.8 on 2025-11-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_eleve_sexe_staff_sexe_alter_staff_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eleve',
            old_name='sexe',
            new_name='genre',
        ),
    ]
