# Generated by Django 5.2.8 on 2025-11-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_sexe_eleve_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='genre',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
