# Generated by Django 5.2.8 on 2025-12-31 22:31

import api.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_enseignant_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliotheque',
            fields=[
                ('id_doc', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('fichier', models.FileField(upload_to='documents/photos/eleve/photo/')),
                ('type_fichier', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bibliotheque',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='interrogation',
            name='cour',
        ),
        migrations.RemoveField(
            model_name='interrogation',
            name='eleve',
        ),
        migrations.AddField(
            model_name='cour',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='disponible',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eleve',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='enseigne',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inscrit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='matiere',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='poste',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='depense',
            name='libelle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DocumentEleve',
            fields=[
                ('id_doc', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('fichier', models.FileField(upload_to=api.models.upload_eleve_path)),
                ('type_fichier', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_eleve', to='api.eleve')),
            ],
            options={
                'db_table': 'documentEleves',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentEnseignant',
            fields=[
                ('id_doc', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('fichier', models.FileField(upload_to=api.models.upload_enseignant_path)),
                ('type_fichier', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_enseignant', to='api.enseignant')),
            ],
            options={
                'db_table': 'documentEnseignants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentEtablissement',
            fields=[
                ('id_doc', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('fichier', models.FileField(upload_to='documents/photos/eleve/photo/')),
                ('type_fichier', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_etablissement', to='api.etablissement')),
            ],
            options={
                'db_table': 'documentEtablissements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentStaff',
            fields=[
                ('id_doc', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('fichier', models.FileField(upload_to=api.models.upload_staff_path)),
                ('type_fichier', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_staff', to='api.staff')),
            ],
            options={
                'db_table': 'documentStaffs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id_eval', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('typeEval', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_cour', to='api.cour')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_eleve', to='api.eleve')),
            ],
            options={
                'db_table': 'evaluations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Occupe',
            fields=[
                ('id_occupe', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_etablissement', to='api.etablissement')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.poste')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_occupations', to='api.staff')),
            ],
            options={
                'db_table': 'occupes',
                'ordering': ['-created_at'],
                'unique_together': {('staff', 'etablissement')},
            },
        ),
        migrations.DeleteModel(
            name='Devoir',
        ),
        migrations.DeleteModel(
            name='Interrogation',
        ),
    ]
